### ISSUE TITLE
Toolips 0.3

### ISSUE THREAD

**Issue by emmaccode** [ChifiSource/Toolips.jl#88]

**Comment by emmettgb** [comment]
don't see this coming anytime soon, but we will see :)

**Comment by emmaccode** [comment]
We are getting really close to the " later this month" release. About to release `ToolipsServables` -- sorry, I haven't had as much time to work on things as anticipated. Been out with a bad back and also distracted + working on other things. This whole thing is still coming soon though, don't worry :)

**Comment by emmaccode** [comment]
Alright ! Both this package && `ToolipsServables` are incredibly close! Just a little more work is required!

**Comment by emmaccode** [comment]
ToolipsServables is essentially done, though I might be doing some more work on documentation and stuff (reason it is unpublished) as well as dox.
Toolips is really close to completion, as well, I am going to go ahead and go through ToolipsSession, Gattino, and ToolipsSVG. Toolips needs just a bit more work to the extensions and Core.jl

**Comment by emmaccode** [comment]
few more things left...
- file interpolation
- changes to parallel processing would be ideal... being able to serve clients from a thread independently, in particular, would be sweet. I think I can do this by making it non-asynchronous otherwise. I might just keep the `ProcessManager` empty until the outside.
- and finally, I am going to

I am going to take some time with `ToolipsSession` and `ToolipsSVG` while creating the tests for this project. Next will be other `Toolips` extensions alongside `Gattino`, before finally I am moving on to `Olive`!

**Comment by emmaccode** [comment]
expect `ToolipsServables` `0.1`, `Toolips` `0.3`, `ToolipsSession` `0.4`, and `ToolipsSVG` `0.2` to all come around the same time; soon, ideally :)

**Comment by emmaccode** [comment]
**Status update**. Almost done with `ToolipsSession` `0.4` as far as the base code goes. I still have to finish `rpc`, I think that is essentially it -- though I am probably also going to make an `Auth` extension add-on as part of that package from now on (to replace `ToolipsAuth`!) With this, I will also make `ToolipsSVG` -- **registering `Toolips 0.3`** as I write the documentation for `ToolipsSVG`. Shortly after, `ToolipsSession 0.4` and going forward `ToolipsUDP 0.2.0`, `ToolipsRemote` etc... New versions. `Gattino` `0.1.0`, `Olive` `0.1.0`. Getting there!

**Comment by emmaccode** [comment]
`ToolipsServables` is out. I have " finished" the RPC features for `ToolipsSession`, they are untested -- currently working on a full implementation that will test it completely and thoroughly. Probably going to also add the `Auth` thing, but renaming this to `SessionAuth` and having an `AuthenticatedConnection` that is used with `convert`/`convert!`.

On the `Toolips` `0.3` front, I pretty much just need to wrap up tests and then we will be good to go. More `README`, docsite, etc. will all come soon after, along with `ToolipsSession`. Problem is I really want this docsite to be on my own hardware. I might rent a nanode exclusively to serve documentation for a bitsy though! :)

**Comment by emmaccode** [comment]
I am going to be waiting *just a little* longer -- only to refine a few minor things. Mainly, I want the `IOConnection` to be compatible with the the `MobileConnection` -- some easy and minor changes. The tests are kind of minimalist, I need to wrap up the `README` -- maybe do some quick scans around. everything seems to be working as intended -- at least right now.
I am also getting painfully close to the `ToolipsSession` `0.4` release, which will come very shortly after this -- likely alongside a release of [ToolipsSVG](https://github.com/ChifiSource/ToolipsSVG.jl). All of these packages are basically ready to use, I just want to make them as perfect as possible -- hoping for a post patch release to be especially brilliant in all of these cases. Really looking forward to it!

**Comment by emmaccode** [comment]
Ok, coming very soon -- I am going to make a mission out of `ToolipsSession` and `ToolipsSVG`, as well -- get these projects out :) Up to `Gattino`. Then `ToolipsUDP`, and `Olive` time. Sure I will work on other stuff along the way; `ToolipsRemote`, for example.

**Comment by emmaccode** [comment]
*guess what*

**Comment by emmaccode** [comment]
@JuliaRegistrator register

(this might not work though, due to `Markdown` (for some reason?) not loaded in current `ToolipsServables` -- no fuss :) 👍🏻

**Comment by emmaccode** [comment]
@JuliaRegistrator register

(this might not work though, due to Markdown (for some reason?) not loaded in current ToolipsServables -- no fuss :) 👍🏻
