### ISSUE TITLE
examples page needs certificate update

### ISSUE THREAD

**Issue by potaslab** [ChifiSource/Toolips.jl#98]
I was trying to look at the examples page but I can't get past firefox's certificate warning. You may need to update your certificates.

**Comment by emmaccode** [comment]
I am sorry, my server has been down for a while.
I am currently in the process of migrating to a new, better server, I just need a few more parts.... I am currently mostly focused on getting one big project out with this, there will be a richer website deployed with many examples -- I just need time. I am sorry -- I created this web-development framework to create a project -- it is really great but definitely lacks in documentation (not for **too** much longer as the other project is nearly at release!)
